use std::{collections::BTreeSet, fs};

const SNIP_COMMANDS: &[&str] = &["start_snip", "get_snip_context", "get_snip_image", "snip_ready", "snip_begin_selection", "complete_snip", "cancel_snip", "copy_snip", "save_snip", "dismiss_snip", "snip_bar_ready"];

// The real invoke handler is the inventory authority. Fail closed on syntax changes
// rather than generating an incomplete app manifest and silently denying old IPC.
fn registered_commands() -> Vec<&'static str> {
    let source = include_str!("src/main.rs");
    let handlers = source.split(".invoke_handler(tauri::generate_handler![").nth(1)
        .expect("missing command inventory").split("])").next().expect("unterminated command inventory");
    let mut commands = BTreeSet::new();
    for handler in handlers.split(',').map(str::trim).filter(|handler| !handler.is_empty()) {
        let command = handler.rsplit("::").next().expect("missing command name");
        assert!(command.bytes().all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_'), "unparsed registered command: {handler}");
        assert!(!handler.starts_with("snipping::") || SNIP_COMMANDS.contains(&command), "new snipping command needs an explicit restricted ACL policy: {command}");
        assert!(commands.insert(command), "duplicate registered command: {command}");
    }
    for command in SNIP_COMMANDS { assert!(commands.contains(*command), "missing sensitive command: {command}"); }
    assert!(commands.len() > SNIP_COMMANDS.len(), "empty legacy inventory");
    commands.into_iter().collect()
}

fn main() {
    println!("cargo:rerun-if-changed=src/main.rs");
    let commands = registered_commands();
    // Before app ACL activation, registered legacy commands were callable from
    // every existing local shell surface; native handlers enforce owner/identity
    // restrictions. Restore that policy, not a new caller-policy redesign. Snip
    // commands never enter this group. Its capability enumerates static labels.
    let mut permission = String::from("# Generated by build.rs from the actual invoke-handler inventory.\n# Do not edit; legacy handler authorization remains enforced in Rust.\n[[permission]]\nidentifier = \"allow-legacy-shell-commands\"\ndescription = \"Restore pre-app-ACL registered legacy command access on existing local shell surfaces; excludes all snipping commands.\"\ncommands.allow = [\n");
    for command in commands.iter().filter(|command| !SNIP_COMMANDS.contains(command)) {
        permission.push_str(&format!("    \"{command}\",\n"));
    }
    permission.push_str("]\n");
    let path = "permissions/legacy-shell.toml";
    if fs::read_to_string(path).ok().as_deref() != Some(permission.as_str()) {
        fs::write(path, permission).expect("write legacy command permission inventory");
    }
    // AppManifest requires a static slice. This one finite allocation belongs to
    // the short-lived build process, never the shell runtime.
    let command_names: &'static [&'static str] = Box::leak(commands.into_boxed_slice());
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(command_names)
    )).expect("tauri build failed");
    // Tauri embeds the application manifest for its main binary, not integration
    // tests/examples. Tauri-linked tests import TaskDialogIndirect, which exists
    // only in Common Controls v6, not the default System32 v5 loader binding.
    #[cfg(target_os = "windows")]
    {
        println!("cargo:rustc-link-arg-examples=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg-examples=/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'");
        println!("cargo:rustc-link-arg-tests=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg-tests=/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'");
    }
}
