export const IPC_COMMANDS = {
  listPinnedTaskbarApps: 'list_pinned_taskbar_apps',
  launchPinnedTaskbarApp: 'launch_pinned_taskbar_app',
  listOpenTaskWindows: 'list_open_task_windows',
  activateTaskWindow: 'activate_task_window',
  maximizeTaskWindow: 'maximize_task_window',
  showTaskWindowPreview: 'show_task_window_preview',
  hideTaskWindowPreview: 'hide_task_window_preview',
  showTaskWindowContextMenu: 'show_task_window_context_menu',
  showLauncherContextMenu: 'show_launcher_context_menu',
  showTopBarPinContextMenu: 'show_top_bar_pin_context_menu',
  showSearchPanel: 'show_search_panel',
  hideSearchPanel: 'hide_search_panel',
  publishSearchPanel: 'publish_search_panel',
  getSearchPanelPayload: 'get_search_panel_payload',
  showProcessManager: 'show_process_manager',
  hideProcessManager: 'hide_process_manager',
  listProcesses: 'list_processes',
  killProcess: 'kill_process',
  searchSystem: 'search_system',
  openShellPath: 'open_shell_path',
  listPinnedStackFolders: 'list_pinned_stack_folders',
  pinStackFolder: 'pin_stack_folder',
  unpinStackFolder: 'unpin_stack_folder',
  reorderPinnedStackFolders: 'reorder_pinned_stack_folders',
  showStackPopup: 'show_stack_popup',
  hideStackPopup: 'hide_stack_popup',
  getStackPopupRequest: 'get_stack_popup_request',
  readStackFolder: 'read_stack_folder',
  openStackItem: 'open_stack_item',
  openStackItemWithPicker: 'open_stack_item_with_picker',
  renameStackItem: 'rename_stack_item',
  copyStackItems: 'copy_stack_items',
  cutStackItems: 'cut_stack_items',
  pasteStackItems: 'paste_stack_items',
  deleteStackItem: 'delete_stack_item',
  newStackFolder: 'new_stack_folder',
  revealStackItem: 'reveal_stack_item',
  reportShellSurfaceRuntimeMetrics: 'report_shell_surface_runtime_metrics',
  loadShellSettings: 'load_shell_settings',
  saveShellSettings: 'save_shell_settings',
  recordDiagnostic: 'record_diagnostic',
  exportDiagnostics: 'export_diagnostics',
  invokeSystemTrayIcon: 'invoke_system_tray_icon'
} as const;

export type IpcCommandName = (typeof IPC_COMMANDS)[keyof typeof IPC_COMMANDS];
