import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const appSource = readFileSync(new URL('../src/App.svelte', import.meta.url), 'utf8');
const surfaceLoaderSource = readFileSync(new URL('../src/lib/surfaceLoader.ts', import.meta.url), 'utf8');
const topBarSource = readFileSync(new URL('../src/components/TopBar.svelte', import.meta.url), 'utf8');
const topBarCss = readFileSync(new URL('../src/components/TopBar.css', import.meta.url), 'utf8');
const commandPanelSource = readFileSync(new URL('../src/components/CommandPanelSurface.svelte', import.meta.url), 'utf8');
const commandPanelCss = readFileSync(new URL('../src/components/CommandPanelSurface.css', import.meta.url), 'utf8');
const shellSurfaceSource = readFileSync(new URL('../src/lib/shellSurface.ts', import.meta.url), 'utf8');
const ipcSurfacesSource = readFileSync(new URL('../src/ipc/surfaces.ts', import.meta.url), 'utf8');
const ipcEventsSource = readFileSync(new URL('../src/ipc/events.ts', import.meta.url), 'utf8');
const ipcCommandsSource = readFileSync(new URL('../src/ipc/commands.ts', import.meta.url), 'utf8');
const commandPanelWrapper = readFileSync(new URL('../src/lib/commandPanel.ts', import.meta.url), 'utf8');
const shellWindowsSource = readFileSync(new URL('../src-tauri/src/shell_windows.rs', import.meta.url), 'utf8');
const mainSource = readFileSync(new URL('../src-tauri/src/main.rs', import.meta.url), 'utf8');
const commandPanelRs = readFileSync(new URL('../src-tauri/src/command_panel.rs', import.meta.url), 'utf8');
const contractsSource = readFileSync(new URL('../src-tauri/src/contracts.rs', import.meta.url), 'utf8');
const capabilitySource = readFileSync(new URL('../src-tauri/capabilities/command-panel.json', import.meta.url), 'utf8');

test('command panel is routed as a dedicated auxiliary shell surface', () => {
  assert.match(appSource, /loadSurfaceComponent\(surface\)/);
  assert.match(surfaceLoaderSource, /'command-panel': \(\) => import\('\.\.\/components\/CommandPanelSurface\.svelte'\)/);
  assert.match(shellSurfaceSource, /\| 'command-panel'/);
  assert.match(shellWindowsSource, /COMMAND_PANEL_LABEL: &str = "command-panel"/);
  assert.match(shellWindowsSource, /COMMAND_PANEL_WIDTH_LOGICAL: f64 = 460\.0/);
  assert.match(shellWindowsSource, /COMMAND_PANEL_HEIGHT_LOGICAL: f64 = 420\.0/);
  assert.match(shellWindowsSource, /build_command_panel_window\(app\)/);
  assert.match(shellWindowsSource, /fn build_command_panel_window\(app: &App\)[\s\S]*?\.resizable\(true\)/);
  assert.match(mainSource, /mod command_panel;/);
  assert.match(mainSource, /command_panel::show_command_panel/);
  assert.match(mainSource, /command_panel::hide_command_panel/);
  assert.match(mainSource, /shell_windows::COMMAND_PANEL_LABEL[\s\S]*WindowEvent::Focused\(false\)/);
  assert.match(mainSource, /emit_to\(\s*shell_windows::TOP_BAR_LABEL,\s*command_panel::COMMAND_PANEL_CLOSED_EVENT/);
  assert.match(commandPanelRs, /pub fn show_command_panel/);
  assert.match(commandPanelRs, /pub fn hide_command_panel/);
  assert.match(commandPanelRs, /pub fn save_command_panel_size/);
  assert.match(capabilitySource, /"command-panel"/);
});

test('command panel contracts and wrappers use constant-backed IPC and event names', () => {
  assert.match(ipcCommandsSource, /showCommandPanel: 'show_command_panel'/);
  assert.match(ipcCommandsSource, /hideCommandPanel: 'hide_command_panel'/);
  assert.match(ipcCommandsSource, /saveCommandPanelSize: 'save_command_panel_size'/);
  assert.match(ipcEventsSource, /commandPanelClosed: 'command-panel:closed'/);
  assert.match(ipcSurfacesSource, /commandPanel: 'command-panel'/);
  assert.match(contractsSource, /COMMAND_PANEL/);
  assert.match(contractsSource, /SHOW_COMMAND_PANEL/);
  assert.match(contractsSource, /HIDE_COMMAND_PANEL/);
  assert.match(contractsSource, /COMMAND_PANEL_CLOSED/);
  assert.match(commandPanelWrapper, /invoke\(IPC_COMMANDS\.showCommandPanel/);
  assert.match(commandPanelWrapper, /invoke\(IPC_COMMANDS\.hideCommandPanel/);
  assert.match(commandPanelWrapper, /invoke\(IPC_COMMANDS\.saveCommandPanelSize/);
  assert.doesNotMatch(commandPanelWrapper, /invoke\('show_command_panel'/);
  assert.doesNotMatch(commandPanelWrapper, /invoke\('hide_command_panel'/);
});

test('top bar command button is left of tray button and enforces popup exclusivity', () => {
  assert.match(topBarSource, /from '\.\.\/lib\/commandPanel'/);
  assert.match(topBarSource, /COMMAND_PANEL_CLOSED_EVENT/);
  assert.match(topBarSource, /class="command-control"[\s\S]*class="tray-control"/);
  assert.match(topBarSource, /class="command-button"[\s\S]*ariaControls=\{COMMAND_PANEL_ID\}/);
  assert.match(topBarSource, /ariaLabel="Open quick commands"/);
  assert.match(topBarSource, /await closePanel\(\);[\s\S]*await closeAudioPanel\(\);[\s\S]*await closeTrayPanel\(\);[\s\S]*await showCommandPanel\(\{/);
  assert.match(topBarSource, /if \(commandOpen && \(!target \|\| !commandControl\?\.contains\(target\)\)\) \{[\s\S]*void closeCommandPanel\(\);/);
  assert.match(topBarSource, /(?:void listen|registerAsyncUnlistener\(listen)\(COMMAND_PANEL_CLOSED_EVENT, \(\) => \{[\s\S]*commandOpen = false;/);
  assert.match(topBarCss, /\.top-bar \.command-button \{/);
  assert.match(topBarSource, /<span class="command-glyph" aria-hidden="true">⌘<\/span>/);
});

test('command panel surface includes compact list actions, resize controls, and command-block editor flow', () => {
  assert.match(commandPanelSource, /id="command-panel"[\s\S]*role="dialog"/);
  assert.match(commandPanelSource, /function selectCommand\(entry: QuickCommandEntry\) \{[\s\S]*startEditEntry\(entry\);[\s\S]*contextEntry = null;[\s\S]*\}/);
  assert.match(commandPanelSource, /data-selected=\{editor\.id === entry\.id\}/);
  assert.doesNotMatch(commandPanelSource, /role="listbox"/);
  assert.doesNotMatch(commandPanelSource, /role="option"/);
  assert.doesNotMatch(commandPanelSource, /aria-selected=\{editor\.id === entry\.id\}/);
  assert.match(commandPanelSource, /on:click=\{\(\) => selectCommand\(entry\)\}/);
  assert.match(commandPanelSource, /on:keydown=\{\(event\) => commandRowKeydown\(event, entry\)\}/);
  assert.match(commandPanelSource, /command-run-button/);
  assert.match(commandPanelSource, /Edit/);
  assert.match(commandPanelSource, /command-delete-button/);
  assert.match(commandPanelSource, /IPC_EVENTS\.quickCommandRunUpdated/);
  assert.match(commandPanelSource, /sendQuickCommandInput/);
  assert.match(commandPanelSource, /normalizeDraftLength/);
  assert.match(commandPanelSource, /pendingInputRequest/);
  assert.match(commandPanelSource, /type="password"/);
  assert.match(commandPanelSource, /Escape/);
  assert.match(commandPanelSource, /One merged transcript/);
  assert.match(commandPanelSource, /class="command-panel-close-button"/);
  assert.doesNotMatch(commandPanelSource, /<p>JasonShell<\/p>/);
  assert.match(commandPanelSource, /class="command-text-button"/);
  assert.match(commandPanelSource, /Saving…/);
  assert.match(commandPanelSource, /Clear/);
  assert.match(commandPanelSource, /Mode/);
  assert.match(commandPanelSource, /Program/);
  assert.match(commandPanelSource, /Working directory/);
  assert.match(commandPanelSource, /Arguments \(one per line\)/);
  assert.match(commandPanelSource, /Commands \(one per line\)/);
  assert.match(commandPanelSource, /parseQuickCommandArgsTextarea/);
  assert.match(commandPanelSource, /formatQuickCommandArgsTextarea/);
  assert.match(commandPanelSource, /parseQuickCommandCommandsTextarea/);
  assert.match(commandPanelSource, /formatQuickCommandCommandsTextarea/);
  assert.match(commandPanelSource, /saveQuickCommandsSettings/);
  assert.match(commandPanelSource, /runQuickCommand/);
  assert.match(commandPanelSource, /quickCommandRunRequest/);
  assert.match(commandPanelSource, /stopQuickCommand/);
  assert.match(commandPanelSource, /listQuickCommandHistory/);
  assert.match(commandPanelSource, /listQuickCommandHistory\(\)/);
  assert.match(commandPanelSource, /const allRuns = await listQuickCommandHistory\(\);/);
  assert.match(commandPanelSource, /const selectedId = editor\.id;/);
  assert.match(commandPanelSource, /Configuration/);
  assert.match(commandPanelSource, /Previous runs/);
  assert.match(commandPanelSource, /\{#each history as run \(historyRunKey\(run\)\)\}/);
  assert.match(commandPanelSource, /class="command-history-list"[\s\S]*\{#if history\.length\}/);
  assert.match(commandPanelSource, /aria-busy=\{historyLoading\}/);
  assert.doesNotMatch(commandPanelSource, /history\.slice\(0, 12\)/);
  assert.match(commandPanelSource, /historyRunStatus/);
  assert.match(commandPanelSource, /if \(saving\) return;/);
  assert.match(commandPanelSource, /const requestId = \+\+historyRequestId;/);
  assert.match(commandPanelSource, /if \(requestId !== historyRequestId \|\| editor\.id !== selectedId\) return;/);
  assert.doesNotMatch(commandPanelSource, /history = \[\];/);
  assert.match(commandPanelSource, /historyLoading = false;/);
  assert.match(commandPanelSource, /on:contextmenu/);
  assert.match(commandPanelSource, /openKeyboardContextMenu/);
  assert.match(commandPanelSource, /on:keydown=\{dismissContextMenuOnEscape\}/);
  assert.match(commandPanelSource, /View output history/);
  assert.match(commandPanelSource, /function showHistory\(\)/);
  assert.match(commandPanelSource, /activeTab = 'previousRuns'/);
  assert.match(commandPanelSource, /One merged transcript/);
  assert.match(commandPanelSource, /command-transcript-line/);
  assert.doesNotMatch(commandPanelSource, /aria-label=\{`Transcript \$\{line\.kind\}`\}/);
  assert.match(commandPanelSource, /transcriptBodySegments/);
  assert.match(commandPanelSource, /TRANSCRIPT_PROMPT_PATTERN/);
  assert.match(commandPanelSource, /TRANSCRIPT_SEGMENT_CACHE_LIMIT/);
  assert.match(commandPanelSource, /transcriptBodySegments\(run\.runId, line\.sequence, `\$\{line\.kind\}:\$\{line\.requestId \?\? line\.body\}:\$\{line\.atEpochMs \?\? ''\}`, line\.body\)/);
  assert.match(commandPanelSource, /sequence === undefined \|\| sequence === null \? `\$\{runId\}:fallback:\$\{fallbackKey\}` : `\$\{runId\}:\$\{sequence\}`/);
  assert.doesNotMatch(commandPanelSource, /TRANSCRIPT_SEGMENT_CACHE_LIMIT \+ 1|> 256/);
  assert.match(commandPanelSource, /historyUpdateFrame/);
  assert.match(commandPanelSource, /requestAnimationFrame/);
  assert.match(commandPanelSource, /cancelAnimationFrame/);
  assert.match(commandPanelCss, /\[data-kind='stderr'\]/);
  assert.match(commandPanelCss, /\[data-kind='system'\]/);
  assert.match(commandPanelCss, /\[data-kind='input-request'\]/);
  assert.match(commandPanelCss, /command-transcript-token--url/);
  assert.match(commandPanelCss, /command-transcript-token--level-error/);
  assert.match(commandPanelCss, /display: block;/);
  assert.match(commandPanelSource, /command-list-resize-grip/);
  assert.match(commandPanelSource, /historyRunStatus/);
  assert.match(commandPanelSource, /activeTab === 'previousRuns'/);
  assert.match(commandPanelSource, /command-history-run/);
  assert.match(commandPanelSource, /<details class="command-history-run" open=\{run\.running \|\| isRunExpanded\(run\)\} on:toggle=\{\(event\) => handleHistoryRunToggle\(event, run\)\}><summary class:running=\{run\.running\} aria-label=\{historyRunSummary\(run\)\}\s*>\s*<div class="command-history-meta">/);
  assert.doesNotMatch(commandPanelSource, /<summary[^>]*on:(?:click|keydown)=/);
  assert.match(commandPanelSource, /command-transcript-shell/);
  assert.match(commandPanelSource, /command-transcript-line/);
  assert.match(commandPanelCss, /user-select:\s*text/);
  assert.match(commandPanelSource, /document\.execCommand\('copy'\)/);
  assert.match(commandPanelSource, /handleTranscriptContextMenu/);
  assert.match(commandPanelSource, /Duplicate command/);
  assert.match(commandPanelSource, /nextDuplicateQuickCommandLabel/);
  assert.match(commandPanelSource, /nextUniqueQuickCommandId/);
  assert.match(commandPanelSource, /\? `Stop \$\{entry\.label\}` : `Run \$\{entry\.label\}`/);
  assert.match(commandPanelSource, /command-stop-button/);
  assert.match(commandPanelSource, /IPC_EVENTS\.quickCommandRunUpdated/);
  assert.match(commandPanelSource, /sendQuickCommandInput/);
  assert.match(commandPanelSource, /pendingInputRequest/);
  assert.match(commandPanelSource, /type="password"/);
  assert.match(commandPanelSource, /Escape/);
  assert.match(commandPanelSource, /One merged transcript/);
  assert.match(commandPanelSource, /Select a command to view runs\./);
  assert.match(commandPanelSource, /command-transcript-line/);
  assert.match(commandPanelCss, /command-transcript-token--path/);
  assert.match(commandPanelCss, /command-transcript-token--level-success/);
  assert.match(commandPanelCss, /\[data-kind='stderr'\]/);
  assert.match(commandPanelCss, /\[data-kind='system'\]/);
  assert.match(commandPanelCss, /\[data-kind='input-request'\]/);
  assert.match(commandPanelCss, /display: block;/);
  assert.match(commandPanelSource, /delete-confirm-backdrop/);
  assert.match(commandPanelSource, /role="alertdialog"/);
  assert.match(commandPanelSource, /bind:this=\{deleteConfirmationDialog\}/);
  assert.match(commandPanelSource, /on:keydown=\{handleDeleteConfirmationKeydown\}/);
  assert.match(commandPanelSource, /deleteConfirmation/);
  assert.match(commandPanelSource, /Cancel/);
  assert.match(commandPanelSource, /Confirm Delete/);
  assert.match(commandPanelSource, /deleteConfirmationBusy/);
  assert.match(commandPanelSource, /focusDeleteConfirmation\(\)/);
  assert.match(commandPanelSource, /restoreDeleteTriggerFocus\(\)/);
  assert.match(commandPanelSource, /const latestRuns = await listQuickCommandHistory\(\{ id \}\);/);
  assert.match(commandPanelSource, /if \(latestRuns\.some\(\(run\) => run\.running\)\) \{[\s\S]*Cannot delete quick command while it is running\./);
  assert.match(commandPanelSource, /event\.key === 'Escape'/);
  assert.match(commandPanelSource, /event\.key !== 'Tab'/);
  assert.match(commandPanelSource, /focusDeleteConfirmationButton\(event\.shiftKey \? -1 : 1\)/);
  assert.match(commandPanelSource, /disabled=\{deleteConfirmationBusy\}/);
  assert.match(commandPanelSource, /let activeRunIds = new Set<string>\(\);/);
  assert.match(commandPanelSource, /let activeCommandIds = new Set<string>\(\);/);
  assert.match(commandPanelSource, /activeRunIds = new Set\(allHistory\.filter\(\(run\) => run\.running\)\.map\(\(run\) => run\.runId\)\);/);
  assert.match(commandPanelSource, /activeCommandIds = new Set\(allHistory\.filter\(\(run\) => run\.running\)\.map\(\(run\) => run\.commandId\)\);/);
  assert.match(commandPanelSource, /Contract: activeCommandIds holds command IDs; freshness map keys must match the same ID domain\./);
  assert.match(commandPanelSource, /function shouldPollHistory\(\): boolean \{[\s\S]*pendingInputRequest !== null[\s\S]*activeRunIds\.size === 0[\s\S]*lastLiveAt === undefined \|\| now - lastLiveAt >= 1100[\s\S]*\}/);
  assert.match(commandPanelSource, /lastLiveHistoryUpdateAtByRun/);
  assert.match(commandPanelSource, /pruneLiveHistoryUpdateTimes\(\)/);
  assert.match(commandPanelSource, /window\.setInterval\(/);
  assert.match(commandPanelSource, /shouldPollHistory\(\)/);
  assert.match(commandPanelSource, /void refreshHistory\(\)/);
  assert.match(commandPanelSource, /historyPollTimer/);
  assert.match(commandPanelCss, /grid-template-columns: minmax\(8rem, var\(--command-list-width\)\)/);
  assert.match(commandPanelCss, /animation: command-spin 1100ms linear infinite/);
  assert.match(commandPanelSource, /hideCommandPanel/);
  assert.match(commandPanelCss, /\.command-panel \{/);
});

test('command panel Rust placement clamps inside monitor work area and shrinks only when needed', () => {
  assert.match(commandPanelRs, /places_command_panel_within_work_area_and_keeps_width_when_it_fits/);
  assert.match(commandPanelRs, /shrinks_command_panel_before_positioning_when_work_area_is_too_narrow/);
  assert.match(commandPanelRs, /clamps_saved_command_panel_size_to_monitor_work_area/);
  assert.match(commandPanelRs, /current_monitor\(\)[\s\S]*?work_area\(\)/);
  assert.match(commandPanelRs, /let target_size = PhysicalSize::new\(panel_width as u32, panel_height as u32\)/);
  assert.match(commandPanelRs, /set_size\(target_size\)/);
  assert.match(commandPanelRs, /emit_to\(TOP_BAR_LABEL, COMMAND_PANEL_CLOSED_EVENT/);
});

test('command panel close lifecycle avoids resize and minimize/maximize disappearance', () => {
  assert.match(mainSource, /COMMAND_PANEL_LABEL[\s\S]*Focused\(false\)/);
  assert.match(mainSource, /sleep\(Duration::from_millis\(150\)\)/);
  assert.match(mainSource, /is_focused\(\)/);
  assert.match(mainSource, /is_maximized\(\)/);
  assert.match(mainSource, /is_minimized\(\)/);
  assert.match(mainSource, /COMMAND_PANEL_LABEL[\s\S]*WindowEvent::Resized/);
  assert.doesNotMatch(mainSource, /COMMAND_PANEL_LABEL[\s\S]*WindowEvent::Maximized/);
  assert.doesNotMatch(mainSource, /COMMAND_PANEL_LABEL[\s\S]*WindowEvent::Minimized/);
});

test('command panel transcript host remains a labelled read-only focusable textbox with copy and context handlers', () => {
  assert.match(
    commandPanelSource,
    /<div class="command-transcript-shell"[^>]*role="textbox"[^>]*aria-readonly="true"[^>]*aria-multiline="true"[^>]*tabindex="0"[^>]*aria-label="Merged transcript"[^>]*on:keydown=\{handleTranscriptKeydown\}[^>]*on:contextmenu=\{handleTranscriptContextMenu\}/,
    'transcript shell should be a focusable labelled read-only textbox and keep copy/context handlers'
  );
});

test('command panel keeps stopping run visible with disabled stop affordance', () => {
  assert.match(commandPanelSource, /latestRunControlKind\(|isRunStopping\(|isCommandStopping\(/);
  assert.match(commandPanelSource, /return run\.running && \(latestRunControlKind\(run\) === 'stopping' \|\| stoppingRunIds\.has\(run\.runId\)\)/);
  assert.match(commandPanelSource, /Stopping…|Stopping\.\.\./);
  assert.match(commandPanelSource, /disabled=\{[^}]*stoppingRunIds\.has|disabled=\{[^}]*isCommandStopping\(/);
  assert.match(commandPanelSource, /<details class="command-history-run" open=\{run\.running \|\| isRunExpanded\(run\)\}/);
});

test('command panel terminal events clear active quick command state immediately', () => {
  assert.match(commandPanelSource, /payload\.kind === 'stopped' \|\| payload\.kind === 'exit'/);
  assert.match(commandPanelSource, /activeRunIds = new Set\(\[\.\.\.activeRunIds\]\.filter\(\(runId\) => runId !== payload\.runId\)\)/);
  assert.match(commandPanelSource, /activeCommandIds = new Set\(\[\.\.\.activeCommandIds\]\.filter\(\(commandId\) => commandId !== payload\.commandId\)\)/);
  assert.match(commandPanelSource, /payload\.kind === 'stop-failed' \|\| payload\.kind === 'stopped' \|\| payload\.kind === 'exit'\) && stoppingId === payload\.commandId\) stoppingId = null/);
});

