import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('process manager surface and commands are routed through app and Rust command table', () => {
  const app = readFileSync('src/App.svelte', 'utf8');
  const surfaces = readFileSync('src/lib/shellSurface.ts', 'utf8');
  const shellWindows = readFileSync('src-tauri/src/shell_windows.rs', 'utf8');
  const main = readFileSync('src-tauri/src/main.rs', 'utf8');
  const bottomBar = readFileSync('src/components/BottomBar.svelte', 'utf8');
  const processSurface = readFileSync('src/components/ProcessManagerSurface.svelte', 'utf8');
  const processState = readFileSync('src/lib/processManagerState.ts', 'utf8');
  const processWrapper = readFileSync('src/lib/processManager.ts', 'utf8');
  const taskbarWindows = readFileSync('src/lib/taskbarWindows.ts', 'utf8');
  const processManager = readFileSync('src-tauri/src/process_manager.rs', 'utf8');
  const taskWindowsMod = readFileSync('src-tauri/src/task_windows/mod.rs', 'utf8');

  assert.match(app, /ProcessManagerSurface/);
  assert.match(surfaces, /'process-manager'/);
  assert.match(shellWindows, /PROCESS_MANAGER_LABEL/);
  assert.match(main, /process_manager::show_process_manager/);
  assert.match(main, /process_manager::list_processes/);
  assert.match(main, /process_manager::kill_process/);
  assert.match(bottomBar, /showProcessManager/);
  assert.match(bottomBar, /process-manager-button/);
  assert.match(processSurface, /sortBy\('startTimeMs'\)/);
  assert.match(processSurface, /formatProcessStartTime\(process\.startTimeMs\)/);
  assert.match(processSurface, /processDeveloperSummary\(process\)/);
  assert.match(processSurface, /listTaskbarProcessWindows/);
  assert.match(processSurface, /buildProcessGroups/);
  assert.match(processSurface, /orderProcessRefresh/);
  assert.match(processSurface, /preserveVolatileOrder/);
  assert.match(processSurface, /processGroups/);
  assert.match(processSurface, /metricAggregates = aggregateProcessMetrics\(visibleProcesses\)/);
  assert.match(processSurface, /formatProcessThreadCount\(metricAggregates\.threadCount\)/);
  assert.match(processSurface, /Threads\{sortIndicator\('threadCount'\)\}/);
  assert.match(processSurface, /class="process-header-metric"/);
  assert.match(processSurface, /class="process-icon"/);
  assert.match(processSurface, /process\.iconDataUrl/);
  assert.match(processSurface, /processGroupExpansionState/);
  assert.match(processSurface, /ariaExpanded=\{groupExpanded\}/);
  assert.match(processSurface, /ariaControls=\{processGroupBodyId\(group\.id\)\}/);
  assert.match(processSurface, /hidden=\{!groupExpanded\}/);
  assert.match(processSurface, /taskbarActivePids/);
  assert.match(processSurface, /buildProcessKillPlan\(processes, process, false\)/);
  assert.match(processSurface, /killConfirmationFromPlan\(killPlan\)/);
  assert.match(processState, /PROCESS_GROUPS/);
  assert.match(processState, /aggregateProcessMetrics/);
  assert.match(processState, /normalizeProcessName/);
  assert.match(processState, /formatProcessThreadCount/);
  assert.match(processState, /classifyProcessGroup/);
  assert.match(processState, /startTimeMs/);
  assert.match(processState, /formatProcessPorts/);
  assert.match(processWrapper, /type ProcessKillConfirmation/);
  assert.match(processWrapper, /iconDataUrl\?: string \| null/);
  assert.match(processWrapper, /taskbarActive/);
  assert.match(processWrapper, /invoke\(IPC_COMMANDS\.killProcess, \{ pid, confirmation \}\)/);
  assert.match(taskbarWindows, /processId/);
  assert.match(taskbarWindows, /listTaskbarProcessWindows/);
  assert.match(taskWindowsMod, /pub process_id: u32/);
  assert.match(taskWindowsMod, /list_taskbar_process_windows/);
  assert.match(processManager, /start_time_ms: process_handle\.and_then\(process_start_time_ms\)/);
  assert.match(processManager, /let command_line = process_handle\.and_then\(process_command_line\)/);
  assert.match(processManager, /command_line,/);
  assert.match(processManager, /listening_ports: listening_ports\.get\(&pid\)/);
  assert.match(processManager, /workspace_hint_from_metadata/);
  assert.match(processManager, /pub icon_data_url: Option<String>/);
  assert.match(processManager, /process_icon_data_url\(executable_path\.as_deref\(\)\)/);
  assert.match(processManager, /build_kill_guardrail_plan/);
  assert.match(processManager, /validate_kill_guardrail_execution/);
});
