import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { test } from 'node:test';
const read = path => readFileSync(new URL(`../src-tauri/${path}`, import.meta.url), 'utf8');
const commands = ['start_snip','snip_bar_ready','get_snip_context','get_snip_image','snip_ready',
  'snip_begin_selection','complete_snip','cancel_snip','copy_snip','save_snip','dismiss_snip'];
const entries = [
  ['snipping-top-bar',['top-bar'],['start_snip','snip_bar_ready']],
  ['snipping-overlay',['snip-overlay-*'],['get_snip_context','get_snip_image','snip_ready','snip_begin_selection','complete_snip','cancel_snip']],
  ['snipping-preview',['snip-preview-*'],['get_snip_context','get_snip_image','copy_snip','save_snip','dismiss_snip']]
];
const permission = command => `allow-${command.replaceAll('_','-')}`;
test('three snipping capabilities grant only exact surface operations and event subscriptions', () => {
  for (const [name,windows,allowed] of entries) {
    const cap=JSON.parse(read(`capabilities/${name}.json`));
    assert.equal(cap.identifier,name); assert.deepEqual(cap.windows,windows);
    assert.deepEqual([...cap.permissions].sort(),[...allowed.map(permission),'core:event:allow-listen','core:event:allow-unlisten'].sort());
    assert.equal(cap.remote,undefined); assert.notEqual(cap.local,false);
    assert.ok(!cap.windows.includes('*'));
  }
  for (const file of readdirSync(new URL('../src-tauri/capabilities/',import.meta.url)).filter(file=>file.endsWith('.json'))) {
    if (entries.some(([name])=>file===`${name}.json`)) continue;
    const cap=JSON.parse(read(`capabilities/${file}`));
    assert.ok(!cap.permissions.some(value=>commands.map(permission).includes(value)),`${file} must not inherit snipping authority`);
  }
});
test('generated permissions expose exactly one command for allow and deny, never default-global snip rights', () => {
  for (const command of commands) {
    // Parse generated restricted TOML permission blocks into identifiers and JSON
    // string arrays. This validates build OUTPUT configuration, not source wiring.
    const blocks=read(`permissions/autogenerated/${command}.toml`).split('[[permission]]').slice(1).map(block=>({
      identifier: JSON.parse(block.match(/^identifier\s*=\s*("[^"]+")/m)[1]),
      allow: block.match(/^commands\.allow\s*=\s*(\[[^\n]+\])/m)?.[1],
      deny: block.match(/^commands\.deny\s*=\s*(\[[^\n]+\])/m)?.[1]
    }));
    assert.equal(blocks.length,2);
    const allow=blocks.find(block=>block.identifier===permission(command));
    const deny=blocks.find(block=>block.identifier===permission(command).replace('allow-','deny-'));
    assert.deepEqual(JSON.parse(allow.allow),[command]); assert.equal(allow.deny,undefined);
    assert.deepEqual(JSON.parse(deny.deny),[command]); assert.equal(deny.allow,undefined);
  }
  const defaultCap=JSON.parse(read('capabilities/default.json'));
  assert.ok(!defaultCap.permissions.includes('default'));
  assert.ok(!defaultCap.permissions.some(value=>commands.map(permission).includes(value)));
});
