export {
  STACK_BROWSER_FRONTEND_EVENTS,
  STACK_BROWSER_BACKGROUND_CONTEXT_MENU_IGNORE_SELECTORS,
  STACK_BROWSER_ROW_HEIGHT_PX,
  STACK_BROWSER_VIRTUAL_MIN_ROWS,
  STACK_BROWSER_VIRTUAL_OVERSCAN_ROWS,
  stackBrowserBreadcrumbOverflow,
  classifyStackMarqueeStartTarget,
  stackBrowserDeletePrompt,
  stackBrowserCreatedTextFileRenamePlan,
  stackBrowserSearchEntries,
  stackBrowserMarqueeRect,
  stackBrowserMarqueeSelectedVirtualPaths,
  stackBrowserMarqueeSelectedPaths,
  stackBrowserContextActionPlans,
  isStackBrowsableArchiveEntry,
  getStackPathAutocompleteQuery,
  getStackPathInlineCompletion,
  getNextStackPathCompletionCycleIndex,
  stackBrowserScrollTopForIndex,
  stackBrowserVirtualWindow,
  type StackBrowserBreadcrumbOverflow,
  type StackBrowserContextActionInput,
  type StackBrowserContextActionKind,
  type StackBrowserContextActionPlan,
  type StackBrowserDeletePrompt,
  type StackBrowserCreatedTextFileRenamePlan,
  type StackBrowserMarqueePoint,
  type StackBrowserMarqueeRect,
  type StackBrowserMarqueeRowBounds,
  type StackBrowserMarqueeVirtualOptions,
  type StackBrowserMarqueeStartTarget,
  type StackBrowserMarqueeStartZone,
  type StackBrowserGitContext,
  type StackBrowserGitOperation,
  type StackBrowserTemplateAction,
  type StackBrowserVirtualOptions,
  type StackBrowserVirtualRow,
  type StackBrowserVirtualWindow,
  type StackPathAutocompleteQuery,
  type StackPathInlineCompletion,
  type StackPathInlineCompletionInput
} from '../../lib/stackPopupViewModel';
